# Generated by Django 5.2.4 on 2025-09-04 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('idambiente', models.AutoField(primary_key=True, serialize=False)),
                ('ambiente', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ambiente',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('idcaracterizacion', models.AutoField(primary_key=True, serialize=False)),
                ('caracterizacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'caracterizacion',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('codigodepartamentos', models.AutoField(primary_key=True, serialize=False)),
                ('departamentos', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(max_length=255, unique=True)),
                ('representanteempresa', models.CharField(max_length=50)),
                ('correoempresa', models.CharField(max_length=200, unique=True)),
                ('nitempresa', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('estados', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('mes1', models.TextField(blank=True, null=True)),
                ('mes2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('idmodalidad', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'modalidad',
            },
        ),
        migrations.CreateModel(
            name='Programaespecial',
            fields=[
                ('idespecial', models.AutoField(primary_key=True, serialize=False)),
                ('programaespecial', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'programaespecial',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Tipoempresa',
            fields=[
                ('idtipoempresa', models.AutoField(primary_key=True, serialize=False)),
                ('tipoempresa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoempresa',
            },
        ),
        migrations.CreateModel(
            name='Tipoidentificacion',
            fields=[
                ('idtipoidentificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipoidentificacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipoidentificacion',
            },
        ),
        migrations.CreateModel(
            name='Tiposolicitud',
            fields=[
                ('idtiposolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tiposolicitud', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tiposolicitud',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('codigomunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=255)),
                ('codigodepartamento', models.ForeignKey(db_column='codigodepartamento', on_delete=django.db.models.deletion.CASCADE, to='Cursos.departamentos')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Programaformacion',
            fields=[
                ('codigoprograma', models.AutoField(primary_key=True, serialize=False)),
                ('verision', models.CharField(max_length=250)),
                ('nombreprograma', models.TextField(blank=True, null=True)),
                ('horas', models.IntegerField()),
                ('idarea', models.ForeignKey(db_column='idarea', on_delete=django.db.models.deletion.CASCADE, to='Cursos.area')),
                ('idmodalidad', models.ForeignKey(db_column='idmodalidad', on_delete=django.db.models.deletion.CASCADE, to='Cursos.modalidad')),
            ],
            options={
                'db_table': 'programaformacion',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idsolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('codigosolicitud', models.IntegerField(blank=True, null=True)),
                ('cupo', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('subsectoreconomico', models.CharField(blank=True, max_length=100, null=True)),
                ('convenio', models.CharField(blank=True, max_length=20, null=True)),
                ('fechasolicitud', models.DateField()),
                ('ambiente', models.ForeignKey(blank=True, db_column='ambiente', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.ambiente')),
                ('codigomunicipio', models.ForeignKey(db_column='codigomunicipio', on_delete=django.db.models.deletion.CASCADE, to='Cursos.municipios')),
                ('codigoprograma', models.ForeignKey(db_column='codigoprograma', on_delete=django.db.models.deletion.CASCADE, to='Cursos.programaformacion')),
                ('idempresa', models.ForeignKey(blank=True, db_column='idempresa', null=True, on_delete=django.db.models.deletion.CASCADE, to='Cursos.empresa')),
                ('idespecial', models.ForeignKey(db_column='idespecial', on_delete=django.db.models.deletion.CASCADE, to='Cursos.programaespecial')),
                ('idhorario', models.ForeignKey(db_column='idhorario', on_delete=django.db.models.deletion.CASCADE, to='Cursos.horario')),
                ('idmodalidad', models.ForeignKey(db_column='idmodalidad', on_delete=django.db.models.deletion.CASCADE, to='Cursos.modalidad')),
                ('idtiposolicitud', models.ForeignKey(db_column='idtiposolicitud', on_delete=django.db.models.deletion.CASCADE, to='Cursos.tiposolicitud')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idficha', models.AutoField(primary_key=True, serialize=False)),
                ('codigoficha', models.IntegerField(unique=True)),
                ('observacion', models.TextField()),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.CASCADE, to='Cursos.estados')),
                ('idsolicitud', models.ForeignKey(db_column='idsolicitud', on_delete=django.db.models.deletion.CASCADE, to='Cursos.solicitud')),
            ],
            options={
                'db_table': 'ficha',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='idtipoempresa',
            field=models.ForeignKey(db_column='idtipoempresa', on_delete=django.db.models.deletion.CASCADE, to='Cursos.tipoempresa'),
        ),
        migrations.CreateModel(
            name='Aspirantes',
            fields=[
                ('idaspirante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('pdf', models.TextField(blank=True, null=True)),
                ('numeroidentificacion', models.IntegerField(unique=True)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('fecha', models.DateField()),
                ('idcaracterizacion', models.ForeignKey(db_column='idcaracterizacion', on_delete=django.db.models.deletion.CASCADE, to='Cursos.caracterizacion')),
                ('solicitudinscripcion', models.ForeignKey(db_column='idsolicitud', on_delete=django.db.models.deletion.CASCADE, to='Cursos.solicitud')),
                ('tipoidentificacion', models.ForeignKey(db_column='tipoidentificacion', on_delete=django.db.models.deletion.CASCADE, to='Cursos.tipoidentificacion')),
            ],
            options={
                'db_table': 'aspirantes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numeroidentificacion', models.IntegerField(unique=True)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.CASCADE, to='Cursos.rol')),
                ('tipoidentificacion', models.ForeignKey(db_column='tipoidentificacion', on_delete=django.db.models.deletion.CASCADE, to='Cursos.tipoidentificacion')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='idusuario',
            field=models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, to='Cursos.usuario'),
        ),
    ]
